# Generated by Django 6.0.6 on 2026-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_num', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('attendence', models.ImageField(upload_to='')),
                ('phone_num', models.IntegerField()),
            ],
        ),
    ]
