# Generated by Django 6.0.6 on 2026-06-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='attendence',
            field=models.IntegerField(),
        ),
    ]
