# Generated by Django 6.0.6 on 2026-06-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0003_students_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='year',
            new_name='backlogs',
        ),
    ]
