# Generated by Django 6.0.6 on 2026-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0004_rename_year_students_backlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.IntegerField()),
                ('password', models.CharField()),
            ],
        ),
    ]
