# Generated by Django 6.0.6 on 2026-06-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0005_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
