# Generated by Django 6.0.6 on 2026-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0006_students_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
