# Generated by Django 6.0.6 on 2026-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0007_alter_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default='G Durga Prasad', max_length=100),
            preserve_default=False,
        ),
    ]
